---
prometheus:
  prometheusOperator:
    prometheusConfigReloader:
      enableProbe: true
      resources:
        requests:
          cpu: 200m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 50Mi